FROM <source_image>
LABEL "Project" = "bcdLab Project | Container for <project_name>"
LABEL "PropertyOf" = "bcdLab Project | User owner of the code"
LABEL "Note" = "This Container is not suposed to be public and it is only for private use in the bcdLab Project System"
LABEL "Version"="1.0"
LABEL "ProjectId" = <project_id>
LABEL "CodeOwnerId" = <user_id>
LABEL "MoreInfo" = "https://bcdlab.xyz"
LABEL "Contact" = "contact@mail.bcdlab.xyz"
<pre_commands>
COPY <source> <destination>
<post_commands>
EXPOSE <ports>
WORKDIR <working_directory>
CMD <command>
